INTEGER
BOOL INT TRUE FALSE VOID PRINTF STRING STRUCT IF THEN ELSE FOR RETURN
MOD AND OR LEFT_CURLY_BRACK RIGHT_CURLY_BRACK COLON RIGHT LEFT
EQUAL_DOUBLE RIGHT_ARROW NOT_EQ NOT LEFT_BRACK RIGHT_BRACK
ADD SUB DOT EQUAL MUL DIV LT GT

%start translation_unit
%%
